server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://sql6.freemysqlhosting.net:3306/sql6454651
    username: sql6454651
    password: iRS2JPrzDM
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: authentication

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.10:8761/eureka/