server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/minorprojectdemo2
    username: root
    password: dakshdaksh
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: authentication