server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/minorprojectdemo2
    username: root
    password: dakshdaksh
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 20MB
  application:
    name: user-project

file:
  upload:
    location: d:/Minor-Project/resources